### ISSUE TITLE
涛思3.0扩展安装方法

### ISSUE THREAD

**Issue by jack361** [Yurunsoft/php-tdengine#11]
大佬你好，涛思现在升级了3.0，我看您也很给力的马上支持了。两个问题请教下：

1.请问下如何安装这个扩展呢？
2.用宝塔面板的话。如何安装这个扩展呢

**Comment by Yurunsoft** [comment]
可以看 README 文件里已经写了如何编译

**Comment by jack361** [comment]
你好，readme文件只写了Linux的，想请教您一下关于Windows系统的安装方法。我现在用的是宝塔面板Windows版本

**Comment by Yurunsoft** [comment]
https://www.baidu.com/s?ie=UTF-8&wd=windows%20php%20%E6%89%A9%E5%B1%95%E7%BC%96%E8%AF%91
