### ISSUE TITLE
请问有支持composer的打算吗

### ISSUE THREAD

**Issue by bioinformatist** [Yurunsoft/php-tdengine#12]
宇润大佬，我们是做锂离子电池生产线MES的，所以会用TDengine存日志和一些流水账，由于IoT场景需要代码热更新也多，所以公司主语言是PHP。

之前一直在用你的RESTful connector，好像3.0之后暂未支持，打算换到这边（也有考虑到效率问题

想问下这个轮子将来会支持composer吗？我打包docker也方便点啦

谢谢！

**Comment by Yurunsoft** [comment]
php-tdengine 是扩展，已经支持了 TDengine 3.0。

RESTful connector 应该是不需要更新也可以支持 3.0，具体可以测试一下，如有问题欢迎在对应的仓库提 issue 或 PR。

**Comment by bioinformatist** [comment]
嗷，我在那边写了[issue](https://github.com/Yurunsoft/tdengine-restful-connector/issues/2)了，要不这边先关啦？

话说这边这个直连的connector不打算支持composer安装的嘛...

**Comment by Yurunsoft** [comment]
扩展没法支持composer安装

**Comment by bioinformatist** [comment]
那倒也是...taos那个client也要手动安装的了

辛苦啦么么哒，RESTful那个如果近期有更新的话我也可以测测给个反馈~
