### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by chensav** [Yurunsoft/php-tdengine#20]
[error.txt](https://github.com/Yurunsoft/php-tdengine/files/10193065/error.txt)
扩展安装成功，执行时报错，
![image](https://user-images.githubusercontent.com/45487582/206658210-a59f9660-f865-409c-8aa6-fe21abda2d2d.png)

**Comment by Yurunsoft** [comment]
错误信息不全

**Comment by chensav** [comment]
@Yurunsoft 修改错误信息了

**Comment by Yurunsoft** [comment]
> @Yurunsoft 修改错误信息了

还是没报错。。。把完整日志复制到文件传上来吧

**Comment by chensav** [comment]
@Yurunsoft 扩展提示安装完成，使用时报错

**Comment by Yurunsoft** [comment]
这个是内存泄漏，请告知下 PHP、TDengine 版本号

然后需要安装 valgrind，执行：
`USE_ZEND_ALLOC=0 valgrind --leak-check=full --log-file=leak.log 这里写上你的php命令`

然后把 `leak.log` 上传上来

**Comment by Yurunsoft** [comment]
另外提供一下复现代码吧

**Comment by chensav** [comment]
php版本 PHP 8.0.26 (cli) (built: Dec  1 2022 16:19:47) ( NTS )

**Comment by chensav** [comment]
php版本 PHP 8.0.26 (cli) 
TDengine Version:3.0.1.8
复现代码 
        \TDengine\setOptions([
            \TDengine\TSDB_OPTION_LOCALE => 'en_US.UTF-8', // 区域
        ]);
[leak.log](https://github.com/Yurunsoft/php-tdengine/files/10193214/leak.log)

**Comment by Yurunsoft** [comment]
检查下你的php是否有问题，看日志是`explode`函数泄露

**Comment by chensav** [comment]
相同版本 centos上会有问题，ubuntu系统上正常

**Comment by chensav** [comment]
@Yurunsoft 这个是直接执行时的日志
[leak (1).log](https://github.com/Yurunsoft/php-tdengine/files/10193673/leak.1.log)

**Comment by Yurunsoft** [comment]
复制下面代码，在你出问题的机器上保存为 `test.c`
```c
#include<stdio.h>

extern char** environ;

int main()
{
    printf("environ=%p\n", environ);
    printf("*environ=%p\n", *environ);
    char **pEnv = environ;
    while (*pEnv != NULL) {
        printf("*pEnv=%s\n", *pEnv);
        pEnv++;
    }
    return 0;
}
```
然后执行：`gcc -o test test.c && ./test`

把结果复制给我
