### ISSUE TITLE
3.0查询数据如何获取上海时区

### ISSUE THREAD

**Issue by xhxh00145** [Yurunsoft/php-tdengine#21]

**Comment by Yurunsoft** [comment]
```php
// 设置客户端选项
\TDengine\setOptions([
    \TDengine\TSDB_OPTION_TIMEZONE => 'Asia/Shanghai', // 时区
]);
```

TDengine 时区问题可参考：https://www.cnblogs.com/taosdata/p/15555957.html

**Comment by xhxh00145** [comment]
已经设置了客户端 但是没生效
![image](https://user-images.githubusercontent.com/44886738/208601594-7a6507f7-36ad-41fa-84e4-8a6d322f5049.png)

**Comment by Yurunsoft** [comment]
建议咨询一下 TDengine 官方，php-tdengine 只是封装个函数，底层逻辑是他们实现的
