### ISSUE TITLE
数据查询错误

### ISSUE THREAD

**Issue by dongyanliang1314** [Yurunsoft/php-tdengine#23]
tdengine：3.0.2.4
php:7.4
php-tdengine:1.0.5
在运行：fetch，或者fetchRow 的时候报错，运行其他的函数都是正常的。
报错信息如下：
[message:protected] => Invalid field type 48
    [string:Exception:private] => 
    [code:protected] => 0

运行的sql很简单:select * from XXX limit 2;
在命令行模式下都是有数据的，用php代码里就报错，这个怎么办

**Comment by Yurunsoft** [comment]
请问你的表结构是怎样的，TDengine 没有类型是 48 的字段类型
