### ISSUE TITLE
安装出现我二体

### ISSUE THREAD

**Issue by kangsange** [Yurunsoft/php-tdengine#24]
运行make出现以下问题：
`g++ -I. -I/www/wwwroot/td/php-tdengine-1.0.5 -DPHP_ATOM_INC -I/www/wwwroot/td/php-tdengine-1.0.5/include -I/www/wwwroot/td/php-tdengine-1.0.5/main -I/www/wwwroot/td/php-tdengine-1.0.5 -I/www/server/php/74/include/php -I/www/server/php/74/include/php/main -I/www/server/php/74/include/php/TSRM -I/www/server/php/74/include/php/Zend -I/www/server/php/74/include/php/ext -I/www/server/php/74/include/php/ext/date/lib -I/usr/local/taos/include -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-deprecated-declarations -Wwrite-strings -std=c++11 -c /www/wwwroot/td/php-tdengine-1.0.5/tdengine.cc  -fPIC -DPIC -o .libs/tdengine.o
In file included from /www/server/php/74/include/php/main/php.h:441:0,
                 from /www/wwwroot/td/php-tdengine-1.0.5/tdengine.cc:7:
/www/wwwroot/td/php-tdengine-1.0.5/include/ext_taos.h: In function ‘void register_constants(int)’:
/www/server/php/74/include/php/Zend/zend_constants.h:62:177: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
 #define REGISTER_NS_STRING_CONSTANT(ns, name, str, flags)  zend_register_string_constant(ZEND_NS_NAME(ns, name), sizeof(ZEND_NS_NAME(ns, name))-1, (str), (flags), module_number)
                                                                                                                                                                                 ^
/www/wwwroot/td/php-tdengine-1.0.5/include/ext_taos.h:19:5: note: in expansion of macro ‘REGISTER_NS_STRING_CONSTANT’
     REGISTER_NS_STRING_CONSTANT("TDengine", "EXTENSION_VERSION", PHP_TDENGINE_VERSION, CONST_CS | CONST_PERSISTENT);
     ^
/www/wwwroot/td/php-tdengine-1.0.5/include/ext_taos.h:20:84: error: invalid conversion from ‘const char*’ to ‘char*’ [-fpermissive]
     REGISTER_NS_STRING_CONSTANT("TDengine", "CLIENT_VERSION", taos_get_client_info(), CONST_CS | CONST_PERSISTENT);
                                                                                    ^
/www/server/php/74/include/php/Zend/zend_constants.h:62:149: note: in definition of macro ‘REGISTER_NS_STRING_CONSTANT’
 #define REGISTER_NS_STRING_CONSTANT(ns, name, str, flags)  zend_register_string_constant(ZEND_NS_NAME(ns, name), sizeof(ZEND_NS_NAME(ns, name))-1, (str), (flags), module_number)
                                                                                                                                                     ^
/www/server/php/74/include/php/Zend/zend_constants.h:86:15: error:   initializing argument 3 of ‘void zend_register_string_constant(const char*, size_t, char*, int, int)’ [-fpermissive]
 ZEND_API void zend_register_string_constant(const char *name, size_t name_len, char *strval, int flags, int module_number);
               ^
make: *** [tdengine.lo] Error 1
`

**Comment by Yurunsoft** [comment]
这个问题修复了，试试 v1.0.6 版本
