### ISSUE TITLE
1.0.6有新的问题

### ISSUE THREAD

**Issue by kangsange** [Yurunsoft/php-tdengine#25]
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:1:
./tdengine_arginfo.h:45:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_query, 0, 1, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:45:1: error: stray '\' in program
./tdengine_arginfo.h:49:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_prepare, 0, 1, TDengine\\Statement, 0)
 ^
./tdengine_arginfo.h:49:1: error: stray '\' in program
./tdengine_arginfo.h:53:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getConnection, 0, 0, TDengine\\Connection, 0)
 ^
./tdengine_arginfo.h:53:1: error: stray '\' in program
./tdengine_arginfo.h:56:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getStatement, 0, 0, TDengine\\Statement, 1)
 ^
./tdengine_arginfo.h:56:1: error: stray '\' in program
./tdengine_arginfo.h:86:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Statement_execute, 0, 0, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:86:1: error: stray '\' in program
/www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:77:74: error: macro "add_assoc_stringl" requires 5 arguments, but only 4 given
                 add_assoc_stringl(zrow, fields[i].name, string_value, len);
                                                                          ^
/www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:140:55: error: macro "add_assoc_string" requires 4 arguments, but only 3 given
         add_assoc_string(&zrow, "name", fields[i].name);
                                                       ^
/www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:171:53: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(resource->sql ? resource->sql : "");
                                                     ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos.h:5,
                 from /www/wwwroot/td/php-tdengine/tdengine.cc:12:
./tdengine_arginfo.h:45:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_query, 0, 1, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:45:1: error: stray '\' in program
./tdengine_arginfo.h:49:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_prepare, 0, 1, TDengine\\Statement, 0)
 ^
./tdengine_arginfo.h:49:1: error: stray '\' in program
./tdengine_arginfo.h:53:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getConnection, 0, 0, TDengine\\Connection, 0)
 ^
./tdengine_arginfo.h:53:1: error: stray '\' in program
./tdengine_arginfo.h:56:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getStatement, 0, 0, TDengine\\Statement, 1)
 ^
./tdengine_arginfo.h:56:1: error: stray '\' in program
./tdengine_arginfo.h:86:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Statement_execute, 0, 0, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:86:1: error: stray '\' in program
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos.cc:1:
./tdengine_arginfo.h:45:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_query, 0, 1, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:45:1: error: stray '\' in program
./tdengine_arginfo.h:49:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_prepare, 0, 1, TDengine\\Statement, 0)
 ^
./tdengine_arginfo.h:49:1: error: stray '\' in program
./tdengine_arginfo.h:53:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getConnection, 0, 0, TDengine\\Connection, 0)
 ^
./tdengine_arginfo.h:53:1: error: stray '\' in program
./tdengine_arginfo.h:56:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getStatement, 0, 0, TDengine\\Statement, 1)
 ^
./tdengine_arginfo.h:56:1: error: stray '\' in program
./tdengine_arginfo.h:86:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Statement_execute, 0, 0, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:86:1: error: stray '\' in program
/www/wwwroot/td/php-tdengine/src/ext_taos.cc:31:38: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
  RETURN_STRING(taos_get_client_info());
                                      ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:1:
./tdengine_arginfo.h:45:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_query, 0, 1, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:45:1: error: stray '\' in program
./tdengine_arginfo.h:49:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_prepare, 0, 1, TDengine\\Statement, 0)
 ^
./tdengine_arginfo.h:49:1: error: stray '\' in program
./tdengine_arginfo.h:53:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getConnection, 0, 0, TDengine\\Connection, 0)
 ^
./tdengine_arginfo.h:53:1: error: stray '\' in program
./tdengine_arginfo.h:56:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getStatement, 0, 0, TDengine\\Statement, 1)
 ^
./tdengine_arginfo.h:56:1: error: stray '\' in program
./tdengine_arginfo.h:86:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Statement_execute, 0, 0, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:86:1: error: stray '\' in program
/www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:126:55: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(statement->sql ? statement->sql : "");
                                                       ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos_connection.h:3,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:1:
./tdengine_arginfo.h:45:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_query, 0, 1, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:45:1: error: stray '\' in program
./tdengine_arginfo.h:49:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Connection_prepare, 0, 1, TDengine\\Statement, 0)
 ^
./tdengine_arginfo.h:49:1: error: stray '\' in program
./tdengine_arginfo.h:53:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getConnection, 0, 0, TDengine\\Connection, 0)
 ^
./tdengine_arginfo.h:53:1: error: stray '\' in program
./tdengine_arginfo.h:56:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Resource_getStatement, 0, 0, TDengine\\Statement, 1)
 ^
./tdengine_arginfo.h:56:1: error: stray '\' in program
./tdengine_arginfo.h:86:1: error: stray '\' in program
 ZEND_BEGIN_ARG_WITH_RETURN_OBJ_INFO_EX(arginfo_class_TDengine_Statement_execute, 0, 0, TDengine\\Resource, 0)
 ^
./tdengine_arginfo.h:86:1: error: stray '\' in program
/www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:69:35: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(connection->host);
                                   ^
/www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:79:35: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(connection->user);
                                   ^
/www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:84:35: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
     RETURN_STRING(connection->pass);
                                   ^
/www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:91:37: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
         RETURN_STRING(connection->db);
                                     ^
/www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:129:33: error: macro "RETURN_STRING" requires 2 arguments, but only 1 given
             RETURN_STRING(result);
                                 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:1:
./tdengine_arginfo.h:4:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_setOptions, 0, 1, _IS_BOOL, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:1:
/usr/include/php/Zend/zend_API.h:105:140: error: expected unqualified-id before ',' token
 #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, sizeof(#name)-1, NULL, 0, type_hint, allow_null, pass_by_ref},
                                                                                                                                            ^
./tdengine_arginfo.h:5:2: note: in expansion of macro 'ZEND_ARG_TYPE_INFO'
  ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
  ^
/usr/include/php/Zend/zend_API.h:111:30: error: expected unqualified-id before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:6:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:1:
./tdengine_arginfo.h:8:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_getClientInfo, 0, 0, IS_STRING, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_resource.cc:1:
/usr/include/php/Zend/zend_API.h:111:30: error: expected declaration before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:9:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
./tdengine_arginfo.h:4:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_setOptions, 0, 1, _IS_BOOL, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/tdengine.cc:7:
/usr/include/php/Zend/zend_API.h:105:140: error: expected unqualified-id before ',' token
 #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, sizeof(#name)-1, NULL, 0, type_hint, allow_null, pass_by_ref},
                                                                                                                                            ^
./tdengine_arginfo.h:5:2: note: in expansion of macro 'ZEND_ARG_TYPE_INFO'
  ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
  ^
/usr/include/php/Zend/zend_API.h:111:30: error: expected unqualified-id before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:6:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos.h:5,
                 from /www/wwwroot/td/php-tdengine/tdengine.cc:12:
./tdengine_arginfo.h:8:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_getClientInfo, 0, 0, IS_STRING, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/tdengine.cc:7:
/usr/include/php/Zend/zend_API.h:111:30: error: expected declaration before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:9:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
make: *** [src/ext_taos_resource.lo] Error 1
make: *** Waiting for unfinished jobs....
make: *** [tdengine.lo] Error 1
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:1:
./tdengine_arginfo.h:4:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_setOptions, 0, 1, _IS_BOOL, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:1:
/usr/include/php/Zend/zend_API.h:105:140: error: expected unqualified-id before ',' token
 #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, sizeof(#name)-1, NULL, 0, type_hint, allow_null, pass_by_ref},
                                                                                                                                            ^
./tdengine_arginfo.h:5:2: note: in expansion of macro 'ZEND_ARG_TYPE_INFO'
  ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
  ^
/usr/include/php/Zend/zend_API.h:111:30: error: expected unqualified-id before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:6:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:1:
./tdengine_arginfo.h:8:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_getClientInfo, 0, 0, IS_STRING, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_statement.cc:1:
/usr/include/php/Zend/zend_API.h:111:30: error: expected declaration before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:9:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
make: *** [src/ext_taos_statement.lo] Error 1
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos.cc:1:
./tdengine_arginfo.h:4:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_setOptions, 0, 1, _IS_BOOL, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos.cc:1:
/usr/include/php/Zend/zend_API.h:105:140: error: expected unqualified-id before ',' token
 #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, sizeof(#name)-1, NULL, 0, type_hint, allow_null, pass_by_ref},
                                                                                                                                            ^
./tdengine_arginfo.h:5:2: note: in expansion of macro 'ZEND_ARG_TYPE_INFO'
  ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
  ^
/usr/include/php/Zend/zend_API.h:111:30: error: expected unqualified-id before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:6:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos.cc:1:
./tdengine_arginfo.h:8:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_getClientInfo, 0, 0, IS_STRING, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos.cc:1:
/usr/include/php/Zend/zend_API.h:111:30: error: expected declaration before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:9:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
make: *** [src/ext_taos.lo] Error 1
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos_connection.h:3,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:1:
./tdengine_arginfo.h:4:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_setOptions, 0, 1, _IS_BOOL, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos_connection.h:3,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:1:
/usr/include/php/Zend/zend_API.h:105:140: error: expected unqualified-id before ',' token
 #define ZEND_ARG_TYPE_INFO(pass_by_ref, name, type_hint, allow_null) { #name, sizeof(#name)-1, NULL, 0, type_hint, allow_null, pass_by_ref},
                                                                                                                                            ^
./tdengine_arginfo.h:5:2: note: in expansion of macro 'ZEND_ARG_TYPE_INFO'
  ZEND_ARG_TYPE_INFO(0, options, IS_ARRAY, 0)
  ^
/usr/include/php/Zend/zend_API.h:111:30: error: expected unqualified-id before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:6:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
In file included from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:54:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos_connection.h:3,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:1:
./tdengine_arginfo.h:8:40: error: expected constructor, destructor, or type conversion before '(' token
 ZEND_BEGIN_ARG_WITH_RETURN_TYPE_INFO_EX(arginfo_TDengine_getClientInfo, 0, 0, IS_STRING, 0)
                                        ^
In file included from /usr/include/php/main/php.h:38:0,
                 from /www/wwwroot/td/php-tdengine/include/ext_tdengine.h:16,
                 from /www/wwwroot/td/php-tdengine/include/ext_taos_connection.h:3,
                 from /www/wwwroot/td/php-tdengine/src/ext_taos_connection.cc:1:
/usr/include/php/Zend/zend_API.h:111:30: error: expected declaration before '}' token
 #define ZEND_END_ARG_INFO()  };
                              ^
./tdengine_arginfo.h:9:1: note: in expansion of macro 'ZEND_END_ARG_INFO'
 ZEND_END_ARG_INFO()
 ^
make: *** [src/ext_taos_connection.lo] Error 1

**Comment by Yurunsoft** [comment]
你的 php 有问题吧 `add_assoc_stringl` 就是 4 个参数的
