### ISSUE TITLE
window 平台有编译好的 DLL 扩展吗？

### ISSUE THREAD

**Issue by stone009** [Yurunsoft/php-tdengine#27]
[系统版本]
window 11

[PHP版本]
8.0.2

因为电脑配置问题，导致一些软件安装不上。没办法源码编译，有已经编译好的大佬麻烦给个 .dll 动态链接库的链接哈~

**Comment by Yurunsoft** [comment]
建议用 restful 组件，不需要安装扩展
https://github.com/Yurunsoft/tdengine-restful-connector
