### ISSUE TITLE
float 类型读取出来的值不精确了，请问下能解决吗?

### ISSUE THREAD

**Issue by xiejunyu** [Yurunsoft/php-tdengine#4]
taos> select * from cell;
           ts                             |          u              |          i                   |         tem            |         soc               |         soh               

 2022-05-29 18:40:27.020 |              3.60000 |             24.00000 |             30.00000 |             50.00000 |             80.00000        
上面是从taos命令查询的出来的数据没问题和插入时的一样

下面是用PHP 查询的
    $resource = $connection->query('select * from cell');
    var_dump($resource->fetch());
 输出
  array(12) {
    ["ts"]=>
    int(1653821412547)
    ["u"]=>
    float(3.5999999046326)
    ["i"]=>
    float(24)
    ["tem"]=>
    float(30.200000762939)
    ["soc"]=>
    float(50.099998474121)
    ["soh"]=>
    float(80.099998474121)
  }
问题： u字段的值本来是3.6的，php取出来变3.5999999046326，soh字段的值本来是80的，php取出来变80.099998474121

**Comment by Yurunsoft** [comment]
`float` 类型本来就是不精确的，建议可以把值存成整数，比如项目中电流保留3位小数，存1就是0.001A
