### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 569344 bytes)

### ISSUE THREAD

**Issue by xiejunyu** [Yurunsoft/php-tdengine#5]
问题:在swoole中运行,不断的执行插入语句,插入到tdengine中,php进程内存会不断的增长不会自动释放,运行了2天内存就超过128M了,直到报错自动停止运行.
执行->query($sql)每插入一个数据,php进程内存都会不断累加

root@ubuntu:/www/wwwroot/192.168.100.127/vendor/simps/mqtt/on# php subscribe.php 
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 569344 bytes) in /www/wwwroot/192.168.100.127/vendor/simps/mqtt/on/subscribe.php on line 126

**Comment by Yurunsoft** [comment]
已修复，请更新 v1.0.3 版本
