### ISSUE TITLE
找不到字段类型常量

### ISSUE THREAD

**Issue by yaoguang97** [Yurunsoft/php-tdengine#8]
环境：
- php7.43
- laravel8.x
- TDengine2.6.08
- php-tdenginev1.02
- ubuntu20.04
![2022-07-23 15-15-24屏幕截图](https://user-images.githubusercontent.com/76577121/180594923-44e07a2a-2e6b-4fd7-a395-85bf0c2c6220.png)

**Comment by Yurunsoft** [comment]
检查拼写，低级问题不要问了，谢谢。

另外建议更新下 php-tdengine 版本
